//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalConundrum2019.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicalConundrums2019Entities : DbContext
    {
        public ClinicalConundrums2019Entities()
            : base("name=ClinicalConundrums2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PayeeInfo> PayeeInfoes { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RequestStatusLookup> RequestStatusLookups { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SpeakerPayment> SpeakerPayments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserStatu> UserStatus { get; set; }
        public virtual DbSet<SessionCreditLookUp> SessionCreditLookUps { get; set; }
        public virtual DbSet<UserTypeLookUp> UserTypeLookUps { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
        public virtual DbSet<ProgramRequestFileUpload> ProgramRequestFileUploads { get; set; }
        public virtual DbSet<ProgramRequestFileUploadOther> ProgramRequestFileUploadOthers { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<AssignedRole> AssignedRoles { get; set; }
        public virtual DbSet<ProgramRequest> ProgramRequests { get; set; }
        public virtual DbSet<HandoutRequest> HandoutRequests { get; set; }
        public virtual DbSet<ProgramRequestSessionCredit> ProgramRequestSessionCredits { get; set; }
        public virtual DbSet<COISlidesUpload> COISlidesUploads { get; set; }
    }
}
