//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalConundrum2019.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandoutRequest
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Number { get; set; }
        public string Language { get; set; }
        public Nullable<System.DateTime> DateRequiredBy { get; set; }
        public string ContactName { get; set; }
        public string EmailAddress { get; set; }
        public string MailingAddress { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> MailToPresenter { get; set; }
        public string PresenterName { get; set; }
        public string PresenterMailingAddress { get; set; }
        public string PresenterCity { get; set; }
        public string PresenterProvince { get; set; }
        public string PresenterPostalCode { get; set; }
        public string AdditionalInfo { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
