//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalConundrum2019.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramRequestFileUploadOther
    {
        public int ProgramRequestID { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
    }
}
