//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalConundrum2019.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramRequestFileUpload
    {
        public int ProgramRequestID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string EvaluationFullPath { get; set; }
        public Nullable<bool> EvaluationUploaded { get; set; }
        public string EvaluationFileName { get; set; }
        public string EvaluationFileExt { get; set; }
        public string SignInFullPath { get; set; }
        public Nullable<bool> SignInUploaded { get; set; }
        public string SignInFileName { get; set; }
        public string SignInFileExt { get; set; }
        public string UserOtherFullPath { get; set; }
        public Nullable<bool> UserOtherUploaded { get; set; }
        public string UserOtherFileName { get; set; }
        public string UserOtherFileExt { get; set; }
        public string SpeakerAgreementFullPath { get; set; }
        public Nullable<bool> SpeakerAgreementUploaded { get; set; }
        public string SpeakerAgreementFileName { get; set; }
        public string SpeakerAgreementFileExt { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string FinalAttendanceListFullPath { get; set; }
        public Nullable<bool> FinalAttendanceListUploaded { get; set; }
        public string FinalAttendanceListFileName { get; set; }
        public string FinalAttendanceListFileExt { get; set; }
    }
}
