//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalConundrum2019.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramRequest
    {
        public int ProgramRequestID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<int> SponsorID { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string SessionAgendaFileName { get; set; }
        public Nullable<bool> SessionAgendaUploaded { get; set; }
        public Nullable<System.DateTime> ProgramDate1 { get; set; }
        public Nullable<System.DateTime> ProgramDate2 { get; set; }
        public Nullable<System.DateTime> ProgramDate3 { get; set; }
        public string SpeakerStatus { get; set; }
        public Nullable<System.DateTime> SpeakerConfirmedProgramDate { get; set; }
        public Nullable<bool> SpeakerProgramDateNA { get; set; }
        public Nullable<System.DateTime> SpeakerConfirmationDate { get; set; }
        public Nullable<bool> SpeakerDeclined { get; set; }
        public Nullable<bool> SpeakerChosenProgramDate { get; set; }
        public string Speaker2Status { get; set; }
        public Nullable<System.DateTime> Speaker2ConfirmedProgramDate { get; set; }
        public Nullable<bool> Speaker2ProgramDateNA { get; set; }
        public Nullable<System.DateTime> Speaker2ConfirmationDate { get; set; }
        public Nullable<bool> Speaker2Declined { get; set; }
        public Nullable<bool> Speaker2ChosenProgramDate { get; set; }
        public string ModeratorStatus { get; set; }
        public Nullable<System.DateTime> ModeratorConfirmedProgramDate { get; set; }
        public Nullable<bool> ModeratorProgramDateNA { get; set; }
        public Nullable<System.DateTime> ModeratorConfirmationDate { get; set; }
        public Nullable<bool> ModeratorDeclined { get; set; }
        public Nullable<bool> ModeratorChosenProgramDate { get; set; }
        public Nullable<System.DateTime> ConfirmedSessionDate { get; set; }
        public Nullable<System.DateTime> MealStartTime { get; set; }
        public Nullable<System.DateTime> ProgramStartTime { get; set; }
        public Nullable<System.DateTime> ProgramEndTime { get; set; }
        public Nullable<decimal> ProgramCredits { get; set; }
        public string MultiSession { get; set; }
        public Nullable<decimal> RegistrationFees { get; set; }
        public Nullable<int> ProgramSpeakerID { get; set; }
        public Nullable<int> ProgramSpeaker2ID { get; set; }
        public Nullable<int> ProgramModeratorID { get; set; }
        public string VenueContacted { get; set; }
        public string LocationType { get; set; }
        public string LocationName { get; set; }
        public string LocationAddress { get; set; }
        public string LocationCity { get; set; }
        public string LocationProvince { get; set; }
        public string LocationPhoneNumber { get; set; }
        public string LocationWebsite { get; set; }
        public Nullable<decimal> CostPerPerson { get; set; }
        public Nullable<decimal> CostByParticipant { get; set; }
        public string MealType { get; set; }
        public string Proximity { get; set; }
        public string AVEquipment { get; set; }
        public string Comments { get; set; }
        public string CancellationReason { get; set; }
        public Nullable<bool> CancellationRequested { get; set; }
        public string ModifyReason { get; set; }
        public Nullable<bool> ModifyRequested { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public string AdminVenueAvailable { get; set; }
        public Nullable<bool> AdminCCASent { get; set; }
        public Nullable<bool> AdminVenueReceipt { get; set; }
        public string AdminVenueNotes { get; set; }
        public Nullable<System.DateTime> AdminCFPCDateSubmitted { get; set; }
        public Nullable<System.DateTime> AdminCFPCDateApproved { get; set; }
        public Nullable<decimal> AdminCFPCFees { get; set; }
        public Nullable<decimal> AdminCFPCImplementationFees { get; set; }
        public Nullable<decimal> AdminCFPCImplementationFeesTaxes { get; set; }
        public Nullable<decimal> AdminCFPCFeesTaxes { get; set; }
        public string AdminSessionID { get; set; }
        public Nullable<decimal> AdminSpeakerHonorium { get; set; }
        public Nullable<decimal> AdminSpeakerHonoriumTaxes { get; set; }
        public Nullable<decimal> AdminSpeakerExpense { get; set; }
        public Nullable<decimal> AdminSpeakerExpenseTaxes { get; set; }
        public Nullable<decimal> AdminSpeaker2Honorium { get; set; }
        public Nullable<decimal> AdminSpeaker2HonoriumTaxes { get; set; }
        public Nullable<decimal> AdminSpeaker2Expense { get; set; }
        public Nullable<decimal> AdminSpeaker2ExpenseTaxes { get; set; }
        public Nullable<decimal> AdminModeratorExpense { get; set; }
        public Nullable<decimal> AdminModeratorExpenseTaxes { get; set; }
        public string AdminSpeakerPaymentMethod { get; set; }
        public Nullable<System.DateTime> AdminSpeakerPaymentSentDate { get; set; }
        public string AdminSpeaker2PaymentMethod { get; set; }
        public Nullable<System.DateTime> AdminSpeaker2PaymentSentDate { get; set; }
        public Nullable<decimal> AdminModeratorHonorium { get; set; }
        public Nullable<decimal> AdminModeratorHonoriumTaxes { get; set; }
        public string AdminModeratorPaymentMethod { get; set; }
        public Nullable<System.DateTime> AdminModeratorPaymentSentDate { get; set; }
        public Nullable<decimal> AdminVenueFees { get; set; }
        public Nullable<decimal> AdminVenueFeesTaxes { get; set; }
        public Nullable<decimal> AdminAVFees { get; set; }
        public Nullable<decimal> AdminAVFeesTaxes { get; set; }
        public Nullable<decimal> AdminOtherFees { get; set; }
        public Nullable<decimal> AdminOtherFeesTaxes { get; set; }
        public Nullable<int> AdminFinalAttendance { get; set; }
        public string AdminActionItems { get; set; }
        public Nullable<bool> AdminEdited { get; set; }
        public Nullable<int> AdminUserID { get; set; }
        public Nullable<System.DateTime> AdminEditDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
        public string AdditionalSessionContact { get; set; }
        public string AdditionalContactName { get; set; }
        public string AdditionalContactPhone { get; set; }
        public string AdditionalContactEmail { get; set; }
        public string EventType { get; set; }
        public string EventTypeQuestion1 { get; set; }
        public string EventTypeQuestion2 { get; set; }
        public string EventTypeQuestion3 { get; set; }
        public string EventTypeQuestion4 { get; set; }
        public string EventTypeQuestion5 { get; set; }
        public Nullable<System.DateTime> RegistrationArrivalTime { get; set; }
        public string MealOption { get; set; }
        public string LocationTypeOther { get; set; }
        public string WebinarEventURL { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual RequestStatusLookup RequestStatusLookup { get; set; }
        public virtual UserInfo SpeakerInfo { get; set; }
        public virtual UserInfo Speaker2Info { get; set; }
        public virtual UserInfo ModeratorInfo { get; set; }
    }
}
