//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicalConundrum2019.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.ProgramRequests = new HashSet<ProgramRequest>();
        }
    
        public int ProgramID { get; set; }
        public Nullable<int> TherapeuticID { get; set; }
        public Nullable<int> ProgramID_CHRC { get; set; }
        public string ProgramName { get; set; }
        public string DevelopedBy { get; set; }
        public string CertifiedBy { get; set; }
        public string ExpirationDate { get; set; }
        public string TargetAudience { get; set; }
        public Nullable<decimal> CreditHours { get; set; }
        public Nullable<System.DateTime> ProgramCompleted { get; set; }
        public Nullable<bool> CustomProgram { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramRequest> ProgramRequests { get; set; }
    }
}
